version: 2.1

orbs:
  spec: moda/spec@0.4.0

workflows:
  specs-validate:
    jobs:
      - spec/specs-validate:
          name: validate
          context: devops-shared-services
          filters:
            branches:
              ignore: master

  specs-publish:
    jobs:
      - spec/specs-publish:
          name: publish-spec-dev
          env: dev
          context: devops-shared-services
          filters:
            branches:
              only: master
      - approve-prod:
          requires:
            - publish-spec-dev
          type: approval
      - spec/specs-publish:
          name: publish-spec-prod
          env: prod
          context: devops-shared-services
          requires:
            - approve-prod
          filters:
            branches:
              only: master